
#ifndef PROTOCOLSOCKET_H
#define PROTOCOLSOCKET_H

enum SocketType {
    CREATE_ROOM,
    JOIN_ROOM,
    LEAVE_ROOM,
    START_ROOM,
    NEXT_QUESTION,
    SEND_ANSWER,
    BAD_RESPONSE,
    FINISH_ROOM,
    REQUEST_ALL_ROOM,
    SEND_REQUEST_ALL_ROOM,
    REQUEST_SAVE_ACTIVE_USER,
    REQUEST_DELETE_ACTIVE_USER,
    FINISH_SAVE_ACTIVE_USER
};

#endif // PROTOCOLSOCKET_H
